### ISSUE TITLE
LICENSE is not in PyPi package

### ISSUE THREAD

**Issue by ukaratay** [sveint/flask-swagger-ui#17]
LICENSE file is not included in PyPi package, causing problem when try to add the package to conda-forge repository.

Please add the license file to the package.

**Comment by jakirkham** [comment]
As FYI, this amounts to adding the following to a `MANIFEST.in` file.

```
include LICENSE
```

**Comment by sveint** [comment]
Thanks, made a new release, also includes LICENSE in package.
