### ISSUE TITLE
Is the project active?

### ISSUE THREAD

**Issue by rafaelcaricio** [sveint/flask-swagger-ui#2]
This project seems interesting. Is there interest to keep the development of this project active? I gave a quick look and seems like it is not up-to-date with the latest version of Swagger UI.

**Comment by sveint** [comment]
Hi,

I use this in an internal project at work, but our needs for the latest versions are probably not as great as yours (looking at the referenced project). Although I'm happy to accept pull requests, I don't plan to keep it updated except for once in a while.

So, probably not as active as you'd want, but if someone wants to help maintain it, I'm happy to assist.

**Comment by rafaelcaricio** [comment]
@sveint Thank you for replying. We are checking for options right now. I just would like to know more clearly what is your intentions with this project.
