### ISSUE TITLE
flask-swagger-ui for local yaml file

### ISSUE THREAD

**Issue by michaldul** [sveint/flask-swagger-ui#22]
As far as I understand get_swaggerui_blueprint() expects address to yaml that is later requested via HTTP. But is it possible to "embed" yaml file at the stage of creating blueprint? (so that the yaml file does not need to be exposed to the world)

**Comment by sveint** [comment]
Please see if https://github.com/sveint/flask-swagger-ui/issues/8 (last comment) solves your problem. Note that the yaml file is naturally exposed to the world regardless, as part of the index.html.

**Comment by michaldul** [comment]
Exactly what I needed. Thanks.
