### ISSUE TITLE
New release on Pypi

### ISSUE THREAD

**Issue by jhinAza** [sveint/flask-swagger-ui#24]
I've seen that the code currently on the master branch allows the use of a blueprint_name parameter, since a PR merged on the 10th of August. I'd need that feature for a project I'm working on. 
We are going to use the workaround described here https://github.com/sveint/flask-swagger-ui/pull/19#issuecomment-404882937, as it's currently a prototype, but I'd prefer the new version as is more elegant. 
¿When are you going to release a new version with this feature?
Thanks!

**Comment by sveint** [comment]
Made a new release now.
