### ISSUE TITLE
Is base_url really needed?

### ISSUE THREAD

**Issue by jeffsawatzky** [sveint/flask-swagger-ui#26]
From what I can tell, base_url is only used in the index.html template to load the static files, which should all be relative to the html file.

I'm currently passing '.' as the base_url, to make all the static files be loaded relative to the html file and it seems to work. So, is this parameter even needed?

**Comment by ZdenekM** [comment]
...thanks for the tip to use '.'

**Comment by jeffsawatzky** [comment]
not using this library anymore so this isn't relevant to me anymore.
