### ISSUE TITLE
examples not working on requestBody

### ISSUE THREAD

**Issue by tamarmot** [sveint/flask-swagger-ui#27]
Per the api specification, requestBody should support example OR examples:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#requestBodyObject

If I include example, it works and shows up in the ui.

If I include examples, it does NOT show up in the ui.
However, I can verify the examples work in this swagger editor:

https://editor.swagger.io/

**Comment by sveint** [comment]
Very late reply, but I believe the version included didn't support multiple examples. The most recent version should fix this issue.
