### ISSUE TITLE
Dynamically generate swagger json or yaml file from multiple Flask Blueprints

### ISSUE THREAD

**Issue by augurs** [sveint/flask-swagger-ui#29]
Hi,
I would like to generate the swagger YML or JSON file of all my routs;
I am using multiple flask blueprint fro creating api routs.

**Comment by whisust** [comment]
Hi, I've just done it, you'll have to write some boilerplate code to generate the file, and use this lib to serve the json + frontend.
I had to combine
```
flask-swagger-ui==3.25.0
dataclasses-jsonschema==2.12.0
apispec==3.3.0
apispec_webframeworks==0.5.2
```
To have automatic api generation from my dataclasses + blueprints
