### ISSUE TITLE
Missing index.template.html

### ISSUE THREAD

**Issue by brunoripa** [sveint/flask-swagger-ui#3]
Because of a missing MANIFEST.in, installing the package from Pypi causes the template not to be copied in the installation.

I will be submitting a msg with a fix.

**Comment by brunoripa** [comment]
Here it is, can you please create the MANIFEST.in containing:

`recursive-include flask_swagger_ui/templates *`

This will make the trick.

**Comment by brunoripa** [comment]
Nevermind, i have forked and created a PR for this:

https://github.com/sveint/flask-swagger-ui/pull/4

**Comment by sveint** [comment]
Sorry for late reply.

I'm unable to reproduce this. The file you mention should already be included as part of `setup.py` configuration. Please reopen if you still experience the problem using the latest version.
