### ISSUE TITLE
Understanding the refresh of swagger files

### ISSUE THREAD

**Issue by robinstauntoncollins** [sveint/flask-swagger-ui#30]
I'm fairly new to flask and swagger.

When I make changes to the 'swagger.yml' file and refresh the page the displayed swagger page seems to be stuck on an old version of the swagger file. Not the new one.

Why does this happen?

I have tried refreshing the page, force refreshing, restarting the flask app entirely. It just seems to get stuck on various older versions.

Is it to do the new version being invalid?

How can I check the validity of the swagger file?

Thanks

**Comment by nzjs** [comment]
Simply using `Ctrl + F5` seems to work for me.
