### ISSUE TITLE
`base_url` is not used when creating the Blueprint

### ISSUE THREAD

**Issue by abak** [sveint/flask-swagger-ui#31]
Ok, this is probably me being thick, but when I do this :

```
swaggerui_blueprint = get_swaggerui_blueprint(
    '/swagger',
    '/specs',
    config={  # Swagger UI config overrides
        'app_name': "Test application"
    })

app.register_blueprint(swaggerui_blueprint)
```
The swagger UI is *not* availalbe on "<host>/swagger".
If I believe the source : https://github.com/sveint/flask-swagger-ui/blob/master/flask_swagger_ui/flask_swagger_ui.py#L14, the `base_url`parameter is not used to create the Blueprint. I need to do:

```
swaggerui_blueprint = get_swaggerui_blueprint(
    '/swagger',
    '/specs',
    config={  # Swagger UI config overrides
        'app_name': "Test application"
    })

swaggerui_blueprint.url_prefix = "/swagger"
app.register_blueprint(swaggerui_blueprint)
```

if i want to achieve the wanted result. Is there something wrong, or is my understanding of the api incorrect ?

**Comment by abak** [comment]
oh yes, i should have read the *entire* README before complaining, feel free to have a laugh and then close this (although i kinda believe that creating the blueprint with the correct prefixx would be slightly better as it would eliminate the possibility for mistakes).

**Comment by sveint** [comment]
Thanks, improved in latest release.
