### ISSUE TITLE
Update to v3.26.0 version

### ISSUE THREAD

**Issue by fescobar** [sveint/flask-swagger-ui#32]
Hi @sveint 
I've recently found a bug related uploading multiple files in swagger-ui
![Screen Shot 2020-06-05 at 12 10 02 PM](https://user-images.githubusercontent.com/1236418/83870124-985bc100-a725-11ea-9e8c-32c9c534eca8.png)

https://github.com/swagger-api/swagger-ui/issues/4600

The fixed was made on this Pull Request.
https://github.com/swagger-api/swagger-ui/pull/6040

I see swagger-ui released a new version `v3.26.0` 
https://github.com/swagger-api/swagger-ui/commit/b9064157e710d0c56d4459b5a7c16751ad0ae72c

<img width="1037" alt="Screen Shot 2020-06-05 at 12 08 27 PM" src="https://user-images.githubusercontent.com/1236418/83869981-5a5e9d00-a725-11ea-80ba-eef27b51ccd4.png">

Please, can you numb a new version of your component for having this fix?

Thank you so much

**Comment by sveint** [comment]
Updated to 3.36.0 now.

**Comment by fescobar** [comment]
@sveint thank you
