### ISSUE TITLE
How to add interceptors via flask-swagger-ui?

### ISSUE THREAD

**Issue by carlosreif** [sveint/flask-swagger-ui#34]
I'm trying to add a requestInteceptor via config but swagger-ui expects a js function

![image](https://user-images.githubusercontent.com/828250/94282400-2a324880-ff26-11ea-98b3-94b1581492ce.png)

```
swaggerui_blueprint = get_swaggerui_blueprint(
    SWAGGER_URL,  # Swagger UI static files will be mapped to '{SWAGGER_URL}/dist/'
    API_URL,
    config={  # Swagger UI config overrides
        'app_name': "Test application",
        'showMutatedRequest': True,
        'requestInterceptor': "function (request) { console.log(request); return request; }" 
    },
)
```

is there anyway to make this work?

**Comment by sveint** [comment]
Hi,

very late reply, sorry about that.

Probably not useful for you anymore, but as it says in the README, config options are currently JSON serialized, so there is no way to achieve this. In theory one could inject the config verbatim into the template and this should work, but that would need some further considerations. I don't really use this myself anymore, so I'll not spend time on that unfortunately.
