### ISSUE TITLE
The swagger-ui package is vulnerable to Cross-site Scripting (XSS)

### ISSUE THREAD

**Issue by marcin-bakowski-dev** [sveint/flask-swagger-ui#48]
SwaggerUI supports displaying remote OpenAPI definitions through the ?url parameter. This enables robust demonstration capabilities on sites like petstore.swagger.io, editor.swagger.io, and similar sites, where users often want to see what their OpenAPI definitions would look like rendered.

Details: https://github.com/swagger-api/swagger-ui/security/advisories/GHSA-qrmm-w75w-3wpx
Is it possible to bump swagger-ui to the latest version v4.1.3?

**Comment by sveint** [comment]
Thanks for the notice and reminder, updated to 4.11.1.

**Comment by thomaxxl** [comment]
thanks a lot!
