### ISSUE TITLE
Using local resource for api url?

### ISSUE THREAD

**Issue by katya111014** [sveint/flask-swagger-ui#7]
This is going to be kind of a dumb question, but I'm trying to narrow down exactly what I'm doing wrong.

I'm working on a small flask project and have been unable to work out how to correctly provide a local resource as my api url. I have my file written, but whether I put it in the base of the project (i.e. where configs, bootstrap, etc live) or the base of the actual flask app (contains app.py, etc), I get the flask ui showing an error message saying "No operations defined in spec!" and a further error message saying that it can't read from the file.

I've checked my permissions, and they all seem right, so I'm trying to figure out what else I could be doing wrong. My only other thought is that I need a sort of internal endpoint to hit, rather than just supplying the file location.

Could you please confirm if there is a particular location the file needs to be in, and/or if it needs to be served to swagger via another endpoint within the application?

**Comment by katya111014** [comment]
Please disregard. I managed to figure out a workaround for my problem.

**Comment by j-chao** [comment]
@katya111014 can you please let me know what your work around was? Thanks!

**Comment by dinko-pehar** [comment]
@j-chao You can check this issue #8 

`get_swaggerui_blueprint` returns blueprint so you can register new route as:

```
swagger_controller = get_swaggerui_blueprint("/docs", "docs/swagger.json")

@swagger_controller.route("/docs/swagger.json")
def expose_swagger():
    return send_file('path/to/swagger.json')
```
Your local file will be exposed at `YOU_API_URL/docs/swagger.json` so when you access `YOU_API_URL/docs`, it will server Swagger-ui documentation
