### ISSUE TITLE
Recommended way to serve .yaml/.json

### ISSUE THREAD

**Issue by rougeth** [sveint/flask-swagger-ui#8]
I'm trying to find the best way to serve locally my swagger.json and set it up to `get_swaggerui_blueprint`. I'm not Flask fluent and the project I'm working on configured a resource that read the json file, load it into a dict and then returns it. Surely there is a better way.

I believe would be better to have an example serving the swagger.json locally on the README.md, since it's probably the most common use.

**Comment by sveint** [comment]
Hi,

sorry for late reply.

This package is purely for serving the Swagger UI itself, acting the same as if you were providing it through another web server. I believe serving any API itself is outside the scope of the package, as it's often very project specific. The best way to view it is to think of the blueprint and the rest of your app as completely separate. What this package does is not really any different from what you get from e.g. http://petstore.swagger.io/ , except you host it locally

You can simply serve the file in question at a resource of your choice in your application (as pure text, json formatted), then pass in the URL for this resource to the blueprint.

I hope this makes sense.

**Comment by rougeth** [comment]
Hi @sveint,
When you say "I believe serving any API itself is outside the scope" you mean the documentation, right? I cannot see how serving the swagger .yaml/.json file too is outside the scope. Certently you can tell better them me, but in my experience, I never saw a case that would make sense split the documentation UI from its "rules" (I'm probably confusing concepts here).

I would love to give a more useful contributing for the project but right now is not a good moment for me :/

Anyway, thanks for the project!!

**Comment by sveint** [comment]
Well, in principle they are decoupled. For instance, in the application where I use this package myself, the swagger json is dynamically created from the REST API endpoints' documentation. I don't have an actual file on my system. I would imagine this being common for many people wanting to use this package.

Also, there can other tools using the swagger.json, which are not related to this package at all.

Creating a resource to serve the file can be as simple as creating a dumb flask resource:

```
# Import flask and create app, then:

@app.route('/api/swagger.json')
def swagger_json():
    # Read before use: http://flask.pocoo.org/docs/0.12/api/#flask.send_file
    return sendfile('path/to/swagger.json')  

swaggerui_blueprint = get_swaggerui_blueprint(
    SWAGGER_URL,
    '/api/swagger.json',
    ...
)
app.register_blueprint(swaggerui_blueprint, url_prefix=SWAGGER_URL)
```

Have you tried this? Is there anything preventing this from working?

**Comment by rougeth** [comment]
Yep, I tried, it worked but it felt strange not having this by default. Well, if only I thought about it, it's an edge case.

@sveint thanks for the discussion! 👍

**Comment by CaveSven** [comment]
For a static yaml file you can do
`
from flask_swagger_ui import get_swaggerui_blueprint
from yaml import Loader, load
from settings import SWAGGER, swagger_path

swagger_yml = load(open(swagger_path, 'r'), Loader=Loader)

blueprint = get_swaggerui_blueprint(SWAGGER_URL, swagger_path, config={'spec': swagger_yml})
`
