### ISSUE TITLE
Swagger ui 3.0.12

### ISSUE THREAD

**Issue by vimalloc** [sveint/flask-swagger-ui#9]
There is a bug in swagger ui 3.0.12 (shipped with this extension) that prevents the 'try it out' button from working: https://github.com/swagger-api/swagger-ui/issues/3146

Any chance this could be updated to a newer version of swaggerui? If you are willing to accept a merge request, I could try my hand at it (but I totally understand if you would want to do that yourself, as you couldn't easily validate that the javascript has not been tampered with).

Thanks for the extension!

**Comment by vimalloc** [comment]
Replacing the dist folder with the newest dist from swagger ui seems to work without a hitch. Hopefully that should be easy to get incorporated.

Cheers!

**Comment by domeniconappo** [comment]
any way to integrate new dist of swagger-ui in this repo ?

**Comment by sveint** [comment]
Sorry for late reply, I've updated it to 3.6.0 now.
